"""is_on column edit

Revision ID: 17e76e933e57
Revises: 498f997657cf
Create Date: 2024-09-18 03:43:11.770211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e76e933e57'
down_revision: Union[str, None] = '498f997657cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IotDevices', sa.Column('state', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('IotDevices', 'is_on')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IotDevices', sa.Column('is_on', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('IotDevices', 'state')
    # ### end Alembic commands ###
