"""is_on column edit

Revision ID: 498f997657cf
Revises: 8cef86e754d5
Create Date: 2024-09-18 00:58:56.342011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498f997657cf'
down_revision: Union[str, None] = '8cef86e754d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IotDevices', sa.Column('is_on', sa.Boolean(), server_default='False', nullable=False))
    op.drop_column('IotDevices', 'Is_ON')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IotDevices', sa.Column('Is_ON', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('IotDevices', 'is_on')
    # ### end Alembic commands ###
