"""adding is_on column

Revision ID: 8cef86e754d5
Revises: 977d8339f46a
Create Date: 2024-09-17 16:25:19.249167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cef86e754d5'
down_revision: Union[str, None] = '977d8339f46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IotDevices', sa.Column('Is_ON', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IotDevices', 'Is_ON')
    # ### end Alembic commands ###
